  version: '3.5'

  services:
    postgres:
      container_name: postgres
      image: postgres
      environment:
        POSTGRES_USER: postgres
        POSTGRES_PASSWORD: postgres
        PGDATA: /data/postgres
      volumes:
        - .pgdata:/data/postgres
      ports:
        - "5432:5432"
      networks:
        - app
      restart: unless-stopped
  

  networks:
    app:
      name: django_app_network
      driver: bridge